### ISSUE TITLE
Nobelist Site only displays 10 nobelists from recent years.

### ISSUE THREAD

**Issue by TheGrandVizier** [Beit-Hatfutsot/wp-nobel#4]
_From @TheGrandVizier on November 29, 2017 10:36_

The Nobelist site does not return results for Nobelists prior and including the year 2001.
When using the slider filter, searching for individuals before 2001 produces no results.

Using the alphabitc filter also produces the same 10 individuals, nothing more.

_Copied from original issue: Beit-Hatfutsot/wp-bh#76_

**Comment by TheGrandVizier** [comment]
_From @nirgoldberg on November 29, 2017 10:47_

@TheGrandVizier, pls attach to https://github.com/Beit-Hatfutsot/wp-nobel

**Comment by nirgoldberg** [comment]
Fixed.
The problem is in GTM (Google Tag Manager) external script.
Theme was rolled back. I'll send a notification to Daniel from SEO Creative to have a look at it.
